filter:
  paths: [src/*]
  excluded_paths: [tests/*]
checks: 
  php: 
    fix_doc_comments: true
    fix_line_ending: true
    fix_linefeed: true
    fix_php_opening_tag: true
    fix_use_statements: 
      order_alphabetically: true
      preserve_blanklines: true
      preserve_multiple: false
      remove_unused: true
    one_class_per_file: true
    remove_extra_empty_lines: true
    remove_php_closing_tag: true
    remove_trailing_whitespace: true
tools:
  external_code_coverage:
    timeout: 1200
    runs: 2
  php_code_coverage: false
  php_code_sniffer: 
    config: 
      standard: PSR2
    filter:
      paths: ['src']
